### ISSUE TITLE
Portaudio file error

### ISSUE THREAD

**Issue by Taher0321** [shivang51/portaudio#1] opened 2023-12-30 16:54 UTC
Hello Shivang,
We are developing a device using vosk and for that we are using your portaudio.lib files. After many repetitions and efforts we are still getting this error: Screenshot attached:
**![WhatsApp Image 2023-12-30 at 10 00 11 PM](https://github.com/shivang51/portaudio/assets/151981876/c9890bac-f1d4-4c0a-b576-d55f3bccc0e7)**

We got a solution on vosk issue page to: "need to link the library itself with -lportaudio, /L only specifies the path."

 We used this command in gcc compiler to implement the above solutions: "gcc speech.cpp -o speech.exe -LC:/path/to/vosk/lib -lvosk -LC:/path/to/portaudio/lib -lportaudio"
 
 But the problem still persists,
 
Can you help us in this error? Kindly help us, let me know if you need more information.

**Comment by shivang51** [comment] 2023-12-30 17:05
Just to make sure can you please provide the exact compilation command you are using.

**Comment by Taher0321** [comment] 2023-12-31 06:53
The command I mentioned above is the exact command

**"gcc speech.cpp -o speech.exe -LC:/path/to/vosk/lib -lvosk -LC:/path/to/portaudio/lib -lportaudio"**

**Comment by shivang51** [comment] 2023-12-31 07:02
Then I guess the problem is that you are not supposed to write paths in windows like this. You should use backslash "\\" instead of frontslash so correct command should be 
`g++ speech.cpp -o speech.exe -L"C:\path\to\vosk\lib" -lvosk -L"C:\path\to\portaudio\lib" -lportaudio`

**Comment by Taher0321** [comment] 2023-12-31 07:11
> Then I guess the problem is that you are not supposed to write paths in windows like this. You should use backslash "\" instead of frontslash so correct command should be `g++ speech.cpp -o speech.exe -L"C:\path\to\vosk\lib" -lvosk -L"C:\path\to\portaudio\lib" -lportaudio`

Still the same problem persists, we implemented this command as per your suggestions: 
g++ speech.cpp -o speech.exe -LC:\vosk\lib -lvosk -LC:\portaudio\lib -lportaudio


Now what do to Shivang?

**Comment by shivang51** [comment] 2023-12-31 07:17
Then I guess path you are specifying is incorrect because assuming you are using this repo without any modifications. Correct path should be `path_to_repo\lib\Static\x64\`.

**Comment by Taher0321** [comment] 2023-12-31 08:50
> Then I guess path you are specifying is incorrect because assuming you are using this repo without any modifications. Correct path should be `path_to_repo\lib\Static\x64\`.

We implemented this solution and the problem we were facing got solved, now this errors is coming:

**Corrupt .drectve at the end of def file**

![WhatsApp Image 2023-12-31 at 2 16 02 PM](https://github.com/shivang51/portaudio/assets/151981876/452667c3-2ac7-4570-95d7-7f5c94c7aac8)

Kindly see the screenshot.

How to solve this error?

**Comment by shivang51** [comment] 2023-12-31 09:03
To fix these errors you to link libs like [winmm](https://stackoverflow.com/questions/28981257/how-to-solve-error-lnk2019-unresolved-external-symbol)  and [bufferoverflow](https://stackoverflow.com/questions/21627607/gcc-linker-error-undefined-reference-to-security-cookie).
Search for other libs accordingly.
Hope this helps.

**Comment by shivang51** [comment] 2023-12-31 09:04
I am closing this issue as library can be linked.

**Closed as completed by shivang51** 2023-12-31 09:04 UTC
